# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_yellowballs(object):
    def setupUi(self, yellowballs):
        yellowballs.setObjectName("yellowballs")
        yellowballs.resize(667, 443)
        self.btn_draw = QtWidgets.QPushButton(yellowballs)
        self.btn_draw.setGeometry(QtCore.QRect(250, 30, 93, 28))
        self.btn_draw.setObjectName("btn_draw")

        self.retranslateUi(yellowballs)
        QtCore.QMetaObject.connectSlotsByName(yellowballs)

    def retranslateUi(self, yellowballs):
        _translate = QtCore.QCoreApplication.translate
        yellowballs.setWindowTitle(_translate("yellowballs", "yellow balls"))
        self.btn_draw.setText(_translate("yellowballs", "draw"))
